spring.application.name=01.sb-acutator-app

management.endpoints.web.exposure.include=*

management.endpoint.shutdown.access=unrestricted

info.application.name=01.sb-actuator-app
info.application.author=Sanjay Patil
info.application.version=1.0.1

management.info.env.enabled=true