spring.application.name=07.sb-security-oauth

spring.security.oauth2.client.registration.google.client-id=345050836844-7r24m5ssugbqrmp46mt0fffobn9l1voc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
